FROM debian:bullseye AS builder

RUN apt-get update && apt-get install -y \
  build-essential \
  gcc \
  g++ \
  libc6-dev \
  libssl-dev \ 
  autoconf \
  automake \
  zlib1g-dev

# -- copy source code from git
COPY openssh-portable /app
WORKDIR /app

# -- configure build
RUN CC=x86_64-linux-gnu-gcc CXX=x86_64-linux-gnu-g++
RUN autoreconf -f -i
RUN ./configure \ 
#  --prefix=/hpnssh_output 
# --prefix=/usr \
# --exec_prefix=/usr \
# --sbindir=/usr/bin \
# --libexecdir=/usr/lib/hpnssh \ 
# --with-privsep-path=/var/empty/sshd \
# --sysconfdir=/etc

# -- setup hpnsshd user
# -- https://www.psc.edu/hpn-ssh-home/hpn-ssh-installation/#step-8-set-up-the-hpnsshd-user
RUN useradd --system --shell /usr/sbin/nologin --comment="Privilege separated HPNSSH User" --home=/run/hpnsshd hpnsshd

# -- make & install
RUN make && make install

# -- add testing user
RUN useradd -rm -d /home/test -s /bin/bash -g root -G sudo -u 1000 test
RUN echo 'test:test' | chpasswd

# -- hpnssh default port is 2222
EXPOSE 2222

# -- start hpn-ssh daemon
CMD ["/usr/local/sbin/hpnsshd", "-D"]

